sudo: false
language: ruby
rvm:
  - 2.2
  - 2.0.0
  - 2.1
  - 1.9.3
  - rbx-2
  - jruby
script: "bundle exec rake"
addons:
  apt:
    packages:
    - idn
before_install:
 - gem update bundler
notifications:
  email:
    recipients:
      - temiola@google.com
    on_success: change
    on_failure: change
